### ISSUE TITLE
How to uninstall old version?

### ISSUE THREAD

**Issue by CodeXTF2** [calebstewart/pwncat#19] opened 2020-06-28 07:03 UTC
How do I uninstall an old copy of pwncat in order to install a modified/updated version?

**Comment by Brazier85** [comment] 2020-06-28 07:43
Did you try to uninstall with:

`pip uninstall pwncat` or  `sudo pip uninstall pwncat`?

**Comment by CodeXTF2** [comment] 2020-06-28 07:45
Yes, it said current version pwncat 0.1 found but then says it cant find files to uninstall. I ran it in verbose mode and it says that it cant find uninstall instructions or smth like that.

**Comment by Brazier85** [comment] 2020-06-28 07:48
Did you install it into a venv or directly? If it it in a venv, just delete it and create a new one. Can you post the log?

**Comment by CodeXTF2** [comment] 2020-06-28 07:50
Direct install. Just reverted a snpashot to remove it so its alll good now :)

**Comment by Brazier85** [comment] 2020-06-28 07:52
Okay, next tine you can try this one: 

Reinstall with:
`python setup.py install --record files.txt`

Then remove all files with:
`xargs rm -rf < files.txt`

**Comment by CodeXTF2** [comment] 2020-06-28 07:52
Ohh, alright. Thanks so much :D

**Comment by calebstewart** [comment] 2020-06-28 16:48
@Brazier85 thanks for responding! I appreciate it.

Also, @CodeXTF2 if you have this issue again, please post the output of the `pip uninstall...` command. It could indicate some issue with the `setup.py` script that I'm not aware of!

**Comment by CodeXTF2** [comment] 2020-06-28 16:50
yeah @calebstewart il do that next time. You should make an uninstall script though, rn whenever i wanna make changes to it I have to run this 2 line script I made to refresh it (from Brazier85's commands) 
```
xargs rm -rf < files.txt
python3 setup.py install --record files.txt
```

If I ever forget and use the setup.py as it is, I need to revert a snapshot to be able to make changes again.

**Comment by calebstewart** [comment] 2020-06-28 17:17
I reopened this issue, because it seems there might actually be a problem that needs fixing. 

The two commands you gave have what I'm assuming is a typo. You said `pip remove`, but that isn't a pip command. It should be `uninstall`. Running this:

```
python3 setup.py install
python3 -m pip uninstall pwncat
```

works fine for me on my machine. I understand it's kind of a pain because it requires you to revert to a snapshot, but if you could retry the troublesome commands, and send the output, it could be helpful. Also, what distribution is your VM running? I may be able to replicate the issue on my end w/ a VM.

**Comment by CodeXTF2** [comment] 2020-06-28 17:26
@calebstewart yeah sorry the remove was a typo. I forget commands all the time xD.

Im running kali 2020 with python 3.8.2. I can go grab the output for you rn from a snapshot, gimme a min il edit this comment with the output.

**Comment by CodeXTF2** [comment] 2020-06-28 17:39
Can you try installing an old version and then installing the current version on top of it (without uninstalling) then running the uninstall command and seeing if the old one remains?

**Comment by CodeXTF2** [comment] 2020-06-29 08:02
Ok, i reproduced the issue after installing it using the venv script on top of an existing direct install.

```
[root@kali:pwncat]# python3 -m pip uninstall pwncat
Found existing installation: pwncat 0.1
Can't uninstall 'pwncat'. No files were found to uninstall.
```

**Comment by calebstewart** [comment] 2020-06-30 01:42
What do you mean by "installing with the venv script?" It sounds like you're doing some weird/unusual things with Python and/or your virtual environment that would be out of scope of this project.

The correct/normal way to install `pwncat` as documented is to use a virtual environment similar to this:

```sh
git clone https://github.com/calebstewart/pwncat
cd pwncat
# You can put your virtual environment anywhere, we'll put it in pwncat/env just as an example
python3 -m venv env
. env/bin/activate
# you can also use `develop` instead of install if you'd like future "pulls" to automatically be used by 
# the installed module. This is a feature of setuptools, not pwncat
python setup.py install 
```

If you'd like to be able to access `pwncat` without entering the virtual environment, you can simply create a symlink to the binary in the virtual environment within your PATH. This is not a feature of `pwncat`, and is simply a side-effect of how virtual environment's and setuptools work:

```sh
# replace $HOME/.local/bin with a directory in your PATH
ln -s /path/to/your/virtualenv/bin/pwncat $HOME/.local/bin
```

# Back on topic...

Your original question was regarding updates/uninstalling. I can't seem to reproduce the issue. In general, you should install/uninstall the same as any other python package. Installing multiple versions of a package on top of one another can always cause issues, although pip normally doesn't allow you to do that. This may be related to the version numbers not changing for pwncat in `setup.py`. Since I hadn't seen this as completely stable yet, I hadn't settled in and started tracking versions diligently. Moving forward I can fix that easily, but there's not really a way to retroactively fix this in old commits. I will start tracking version numbers on commits moving forward, however.

I don't feel comfortable moving to a `1.0.0` at this time. Like I said, I will start keeping semantic versioning moving forward (still <1.0). That being said, as this is still <1.0, there will likely be a lot of changes. I keep my working and testing copies up to date with the `develop` target of `setuptools`. When installing a package with setuptools, you can use `develop` instead of `install`, which basically symlinks the repository source to the python packages directory. This allows modifications of the source code to be reflected in the installed package (e.g. after a `git pull`). At least until I get to a stable `v1.0.0` release, I would recommend tracking changes this way. An update should be as simple as `git pull`. This isn't official instructions in the documentation, as it's more of a developmental feature than actual end user instructions. Mileage may vary.

**Comment by CodeXTF2** [comment] 2020-06-30 08:32
Ah alright! Thanks for the help! Yeah I understand, makes sense. My current installation is stable, (hopefully stays that way) yesterday when I reproduced the issue (as you said, doing some weird  things with python) I was deliberately trying to recreate that error since you asked me to revert to that snapshot and grab the error in case it helped you :)

**Comment by calebstewart** [comment] 2020-07-02 13:06
I'm going to close this issue. It sounds like it's more of an issue of edge cases in handling setuptools packages than an issue in pwncat itself.

**Closed by calebstewart** 2020-07-02 13:06 UTC
