### ISSUE TITLE
[BUG] SQL Database OperationalError when using `download` with two concurrent sessions open

### ISSUE THREAD

**Issue by JohnHammond** [calebstewart/pwncat#64] opened 2020-10-16 02:01 UTC
_If you are pasting terminal output or code snippets, place them in a code block (three backticks) in accordance with Markdown formatting for easier reading_

**Describe the bug**
When running two instances of pwncat on the same target, I receive an `OperationalError: the database is locked` when attempting to download a file.

**Describe the target system**
Provide as much detail about the target host as possible. If this is a TryHackMe or Hack The Box or similar machine, please provide the machine name and/or link as well.

This is the Blunder machine from HackTheBox

**To Reproduce**
1. Get pwncat listening for a reverse shell on one port and have the victim connect.
2. Start a SECOND pwncat reverse shell listener on the SAME port and have the victim connect again.
3. Attempt to download a file with the local `download filename.txt` command

**Expected behavior**
Correct download. (it does work with just one session connected)

**Error and traceback**

```
(local) pwncat$ download D5100_EN.pdf                                                                   
╭───────────────────────────────── Traceback (most recent call last) ──────────────────────────────────╮
│ /home/john/git/pwncat/pwncat/commands/__init__.py:232 in run                                         │
│                                                                                                      │
│   229                 if line == "":                                                                 │
│   230                     continue                                                                   │
│   231                                                                                                │
│ ❱ 232                 self.dispatch_line(line)                                                       │
│   233             # We used to catch only KeyboardException, but this prevents a                     │
│   234             # badly written command from completely killing our remote                         │
│   235             # connection.                                                                      │
│                                                                                                      │
│ /home/john/git/pwncat/pwncat/commands/__init__.py:309 in dispatch_line                               │
│                                                                                                      │
│   306                 args = line                                                                    │
│   307                                                                                                │
│   308             # Run the command                                                                  │
│ ❱ 309             command.run(args)                                                                  │
│   310                                                                                                │
│   311             if prog_name:                                                                      │
│   312                 command.parser.prog = prog_name                                                │
│                                                                                                      │
│ /home/john/git/pwncat/pwncat/commands/download.py:63 in run                                          │
│                                                                                                      │
│   60             )                                                                                   │
│   61                                                                                                 │
│   62         try:                                                                                    │
│ ❱ 63             length = pwncat.victim.get_file_size(args.source)                                   │
│   64             started = time.time()                                                               │
│   65             with progress:                                                                      │
│   66                 task_id = progress.add_task(                                                    │
│                                                                                                      │
│ /home/john/git/pwncat/pwncat/remote/victim.py:1243 in get_file_size                                  │
│                                                                                                      │
│   1240         :return: int                                                                          │
│   1241         """                                                                                   │
│   1242                                                                                               │
│ ❱ 1243         stat = self.which("stat")                                                             │
│   1244         if stat is None:                                                                      │
│   1245             return None                                                                       │
│   1246                                                                                               │
│                                                                                                      │
│ /home/john/git/pwncat/pwncat/remote/victim.py:667 in which                                           │
│                                                                                                      │
│    664                                                                                               │
│    665         binary = (                                                                            │
│    666             self.session.query(pwncat.db.Binary)                                              │
│ ❱  667             .filter_by(name=name, host_id=self.host.id)                                       │
│    668             .first()                                                                          │
│    669         )                                                                                     │
│    670         if binary is not None:                                                                │
│                                                                                                      │
│ /home/john/git/pwncat/env/lib/python3.8/site-packages/SQLAlchemy-1.3.18-py3.8-linux-x86_64.egg/sqlal │
│ chemy/orm/attributes.py:287 in __get__                                                               │
│                                                                                                      │
│    284         if self._supports_population and self.key in dict_:                                   │
│    285             return dict_[self.key]                                                            │
│    286         else:                                                                                 │
│ ❱  287             return self.impl.get(instance_state(instance), dict_)                             │
│    288                                                                                               │
│    289                                                                                               │
│    290 def create_proxied_attribute(descriptor):                                                     │
│                                                                                                      │
│ /home/john/git/pwncat/env/lib/python3.8/site-packages/SQLAlchemy-1.3.18-py3.8-linux-x86_64.egg/sqlal │
│ chemy/orm/attributes.py:718 in get                                                                   │
│                                                                                                      │
│    715                     return PASSIVE_NO_RESULT                                                  │
│    716                                                                                               │
│    717                 if key in state.expired_attributes:                                           │
│ ❱  718                     value = state._load_expired(state, passive)                               │
│    719                 elif key in state.callables:                                                  │
│    720                     callable_ = state.callables[key]                                          │
│    721                     value = callable_(state, passive)                                         │
│                                                                                                      │
│ /home/john/git/pwncat/env/lib/python3.8/site-packages/SQLAlchemy-1.3.18-py3.8-linux-x86_64.egg/sqlal │
│ chemy/orm/state.py:652 in _load_expired                                                              │
│                                                                                                      │
│   649                                                                                                │
│   650         toload = self.expired_attributes.intersection(self.unmodified)                         │
│   651                                                                                                │
│ ❱ 652         self.manager.deferred_scalar_loader(self, toload)                                      │
│   653                                                                                                │
│   654         # if the loader failed, or this                                                        │
│   655         # instance state didn't have an identity,                                              │
│                                                                                                      │
│ /home/john/git/pwncat/env/lib/python3.8/site-packages/SQLAlchemy-1.3.18-py3.8-linux-x86_64.egg/sqlal │
│ chemy/orm/loading.py:1008 in load_scalar_attributes                                                  │
│                                                                                                      │
│   1005             )                                                                                 │
│   1006             return                                                                            │
│   1007                                                                                               │
│ ❱ 1008         result = load_on_ident(                                                               │
│   1009             session.query(mapper),                                                            │
│   1010             identity_key,                                                                     │
│   1011             refresh_state=state,                                                              │
│                                                                                                      │
│ /home/john/git/pwncat/env/lib/python3.8/site-packages/SQLAlchemy-1.3.18-py3.8-linux-x86_64.egg/sqlal │
│ chemy/orm/loading.py:201 in load_on_ident                                                            │
│                                                                                                      │
│    198     else:                                                                                     │
│    199         ident = identity_token = None                                                         │
│    200                                                                                               │
│ ❱  201     return load_on_pk_identity(                                                               │
│    202         query,                                                                                │
│    203         ident,                                                                                │
│    204         refresh_state=refresh_state,                                                          │
│                                                                                                      │
│ /home/john/git/pwncat/env/lib/python3.8/site-packages/SQLAlchemy-1.3.18-py3.8-linux-x86_64.egg/sqlal │
│ chemy/orm/loading.py:287 in load_on_pk_identity                                                      │
│                                                                                                      │
│    284     q._order_by = None                                                                        │
│    285                                                                                               │
│    286     try:                                                                                      │
│ ❱  287         return q.one()                                                                        │
│    288     except orm_exc.NoResultFound:                                                             │
│    289         return None                                                                           │
│    290                                                                                               │
│                                                                                                      │
│ /home/john/git/pwncat/env/lib/python3.8/site-packages/SQLAlchemy-1.3.18-py3.8-linux-x86_64.egg/sqlal │
│ chemy/orm/query.py:3458 in one                                                                       │
│                                                                                                      │
│   3455                                                                                               │
│   3456         """                                                                                   │
│   3457         try:                                                                                  │
│ ❱ 3458             ret = self.one_or_none()                                                          │
│   3459         except orm_exc.MultipleResultsFound as err:                                           │
│   3460             util.raise_(                                                                      │
│   3461                 orm_exc.MultipleResultsFound(                                                 │
│                                                                                                      │
│ /home/john/git/pwncat/env/lib/python3.8/site-packages/SQLAlchemy-1.3.18-py3.8-linux-x86_64.egg/sqlal │
│ chemy/orm/query.py:3427 in one_or_none                                                               │
│                                                                                                      │
│   3424             :meth:`_query.Query.one`                                                          │
│   3425                                                                                               │
│   3426         """                                                                                   │
│ ❱ 3427         ret = list(self)                                                                      │
│   3428                                                                                               │
│   3429         l = len(ret)                                                                          │
│   3430         if l == 1:                                                                            │
│                                                                                                      │
│ /home/john/git/pwncat/env/lib/python3.8/site-packages/SQLAlchemy-1.3.18-py3.8-linux-x86_64.egg/sqlal │
│ chemy/orm/query.py:3503 in __iter__                                                                  │
│                                                                                                      │
│   3500         context.statement.use_labels = True                                                   │
│   3501         if self._autoflush and not self._populate_existing:                                   │
│   3502             self.session._autoflush()                                                         │
│ ❱ 3503         return self._execute_and_instances(context)                                           │
│   3504                                                                                               │
│   3505     def __str__(self):                                                                        │
│   3506         context = self._compile_context()                                                     │
│                                                                                                      │
│ /home/john/git/pwncat/env/lib/python3.8/site-packages/SQLAlchemy-1.3.18-py3.8-linux-x86_64.egg/sqlal │
│ chemy/orm/query.py:3524 in _execute_and_instances                                                    │
│                                                                                                      │
│   3521         return conn                                                                           │
│   3522                                                                                               │
│   3523     def _execute_and_instances(self, querycontext):                                           │
│ ❱ 3524         conn = self._get_bind_args(                                                           │
│   3525             querycontext, self._connection_from_session, close_with_result=True               │
│   3526         )                                                                                     │
│   3527                                                                                               │
│                                                                                                      │
│ /home/john/git/pwncat/env/lib/python3.8/site-packages/SQLAlchemy-1.3.18-py3.8-linux-x86_64.egg/sqlal │
│ chemy/orm/query.py:3539 in _get_bind_args                                                            │
│                                                                                                      │
│   3536         return conn.execute(stmt, self._params)                                               │
│   3537                                                                                               │
│   3538     def _get_bind_args(self, querycontext, fn, **kw):                                         │
│ ❱ 3539         return fn(                                                                            │
│   3540             mapper=self._bind_mapper(), clause=querycontext.statement, **kw                   │
│   3541         )                                                                                     │
│   3542                                                                                               │
│                                                                                                      │
│ /home/john/git/pwncat/env/lib/python3.8/site-packages/SQLAlchemy-1.3.18-py3.8-linux-x86_64.egg/sqlal │
│ chemy/orm/query.py:3518 in _connection_from_session                                                  │
│                                                                                                      │
│   3515         return str(context.statement.compile(bind))                                           │
│   3516                                                                                               │
│   3517     def _connection_from_session(self, **kw):                                                 │
│ ❱ 3518         conn = self.session.connection(**kw)                                                  │
│   3519         if self._execution_options:                                                           │
│   3520             conn = conn.execution_options(**self._execution_options)                          │
│   3521         return conn                                                                           │
│                                                                                                      │
│ /home/john/git/pwncat/env/lib/python3.8/site-packages/SQLAlchemy-1.3.18-py3.8-linux-x86_64.egg/sqlal │
│ chemy/orm/session.py:1138 in connection                                                              │
│                                                                                                      │
│   1135         if bind is None:                                                                      │
│   1136             bind = self.get_bind(mapper, clause=clause, **kw)                                 │
│   1137                                                                                               │
│ ❱ 1138         return self._connection_for_bind(                                                     │
│   1139             bind,                                                                             │
│   1140             close_with_result=close_with_result,                                              │
│   1141             execution_options=execution_options,                                              │
│                                                                                                      │
│ /home/john/git/pwncat/env/lib/python3.8/site-packages/SQLAlchemy-1.3.18-py3.8-linux-x86_64.egg/sqlal │
│ chemy/orm/session.py:1146 in _connection_for_bind                                                    │
│                                                                                                      │
│   1143                                                                                               │
│   1144     def _connection_for_bind(self, engine, execution_options=None, **kw):                     │
│   1145         if self.transaction is not None:                                                      │
│ ❱ 1146             return self.transaction._connection_for_bind(                                     │
│   1147                 engine, execution_options                                                     │
│   1148             )                                                                                 │
│   1149         else:                                                                                 │
│                                                                                                      │
│ /home/john/git/pwncat/env/lib/python3.8/site-packages/SQLAlchemy-1.3.18-py3.8-linux-x86_64.egg/sqlal │
│ chemy/orm/session.py:409 in _connection_for_bind                                                     │
│                                                                                                      │
│    406             self._parent._key_switches.update(self._key_switches)                             │
│    407                                                                                               │
│    408     def _connection_for_bind(self, bind, execution_options):                                  │
│ ❱  409         self._assert_active()                                                                 │
│    410                                                                                               │
│    411         if bind in self._connections:                                                         │
│    412             if execution_options:                                                             │
│                                                                                                      │
│ /home/john/git/pwncat/env/lib/python3.8/site-packages/SQLAlchemy-1.3.18-py3.8-linux-x86_64.egg/sqlal │
│ chemy/orm/session.py:289 in _assert_active                                                           │
│                                                                                                      │
│    286         elif self._state is DEACTIVE:                                                         │
│    287             if not deactive_ok and not rollback_ok:                                           │
│    288                 if self._rollback_exception:                                                  │
│ ❱  289                     raise sa_exc.InvalidRequestError(                                         │
│    290                         "This Session's transaction has been rolled back "                    │
│    291                         "due to a previous exception during flush."                           │
│    292                         " To begin a new transaction with this Session, "                     │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────╯
InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during 
flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception 
was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this
flush is occurring prematurely)
(sqlite3.OperationalError) database is locked
[SQL: INSERT INTO history (host_id, command) VALUES (?, ?)]
[parameters: (2, 'ls')]
(Background on this error at: http://sqlalche.me/e/13/e3q8) (Background on this error at: 
http://sqlalche.me/e/13/7s2a)
```

**Comment by calebstewart** [comment] 2020-10-16 02:40
I have a suspicion this is caused by bad database practices on my end, but may be due to `sqlite` multi-process requirements. I'm going to dig into the sqlite documentation to try and figure out if it's my implementation that is flawed or if multi-writer access is just not well supported in sqlite. Either is equally possible, to be honest. I'm not fully confident in how I'm interacting with the database and `sqlite` isn't a production database server by any means.

**Comment by calebstewart** [comment] 2021-05-05 03:19
So, in light of moving away from traditional SQL databases in the upcoming branch as well upcoming support for multi-session instances of `pwncat`, I'm going to close this issue.

**Closed by calebstewart** 2021-05-05 03:19 UTC
Labels: bug
