### ISSUE TITLE
FYI - FFM + naming issue

### ISSUE THREAD

**Issue by noraj** [calebstewart/pwncat#18] opened 2020-06-18 20:27 UTC
You may interested to know an existing similar tool: [Freedom Fighting Mode (FFM)](https://github.com/JusticeRage/FFM) that the author calls a "hacking harness".
It can allocates pty, remove history, allow download/upload, normalize etc.
It's also in python so it may inspire you for new features.

**Comment by noraj** [comment] 2020-06-20 16:30
Also the naming is very problematic with the "real" pwncat

- https://github.com/cytopia/pwncat
- http://pwncat.org/
- pwncat - netcat on steroids with Firewall, IDS/IPS evasion, bind and reverse shell, self-injecting shell and port forwarding magic - and its fully scriptable with Python (PSE)

**Comment by calebstewart** [comment] 2020-06-28 17:00
Sorry for the delay. I appreciate the heads up. 

I'm unsure what the intent of the issue is, though. The two projects were started within a month of each other from what I can see on GitHub. I learned of the other "pwncat" a couple weeks ago, but wasn't too worried about it. Cytopia is obviously worried more about marketing than I am. That being said, is the conflict due to trying to get this added to BlackArch?

**Comment by noraj** [comment] 2020-06-29 08:57
For my concern only, there is already a pwncat package on blackarch, having too similar tool with exactly the same name is problematic.

**Comment by cytopia** [comment] 2020-07-18 12:59
> Cytopia is obviously worried more about marketing than I am.

That sounds a bit harsh or. _That being said_, we've all been a bit late to the naming game anyway :-)

https://github.com/owlinux1000/pwncat

![Screenshot 2020-07-11 10-42-13  selection](https://user-images.githubusercontent.com/12533999/87852918-5b7b1080-c906-11ea-847e-6271542000d4.png)



Saw your tool in action in [King of the Hill](https://www.youtube.com/watch?v=B7YoMwBYAOU) - pretty cool btw! (also enjoyed the part when John was trying to pronounce my name at the end)

**Comment by calebstewart** [comment] 2020-07-18 14:55
Oh, wasn't meant to be harsh at all! I simply meant that you had obviously spent more time solidifying a "brand" between the website, logo, etc. No hard feelings I hope!

John and I have discussed the correct pronunciation, and haven't come to a conclusion 😆

**Comment by calebstewart** [comment] 2020-07-20 01:25
I'm going to close this, as honestly, I can't think of a better name and I don't know what solution I could possibly provide. Thanks for the heads up, though!

**Closed by calebstewart** 2020-07-20 01:25 UTC
