### ISSUE TITLE
[BUG] pwncat in the terminal

### ISSUE THREAD

**Issue by Anteste** [calebstewart/pwncat#74] opened 2020-12-17 11:08 UTC
**Describe the bug**
When I launch pwncat I don't know why but it isn't shown correctly

**Describe the target system**
The Target host is TryHackMe teh DogCat Room

**Screenshot**
![image](https://user-images.githubusercontent.com/47607954/102480350-0fb8c880-4058-11eb-9684-eea4735dd962.png)

Why do I have that bug ?
\[\](remote)\[\] \[\]www-data@88fe22526dbb\[\]:\[\]/\[\]$

**Comment by JohnHammond** [comment] 2021-01-03 03:40
You look to be running in `/bin/sh`, which may act strangely with the
prompt. You can either invoke `bash` within your pwncat shell, or try to
use a bash reverse shell.

**Comment by Jul0ow** [comment] 2021-01-16 19:43
I have the same problem and my shell is completely broken (cannot Ctrl+Z or use my arrows) do somebody knows why ?

**Comment by Anteste** [comment] 2021-01-18 21:21
I was on Parrot Os , when I moved to Kali everything was fixed 🤷‍♂️

**Comment by Jul0ow** [comment] 2021-01-19 17:35
I'm in kali right now and the problem is still there

**Comment by andy2002a** [comment] 2021-01-26 17:12
I've been having this issue too. Sometime uploading a file (Ctrl+D > Upload) then going back to the terminal (Ctrl + D again) fixes the issue.

**Comment by calebstewart** [comment] 2021-05-05 03:37
To summarize the above problems, it seems there are intermittent issues with the state of the remote terminal. `pwncat` allocates a `pty` for you on the victim end, and if the settings for that pty are not correct, weird things can happen. There's also the issue of *very* **very** basic shells that don't support normal interactive elements such as arrow keys or C-c/C-z. Namely, a POSIX-compliant `sh` implementation will not behave like you expect.

There's not much `pwncat` can do about the second part. If you run `/bin/sh` or `/bin/dash`, you may find some odd things related to formatting or interactivity, because interactivity is explicitly not a goal of those shells. For the former problem (`stty` settings), we try to normalize those settings in `pwncat`, but sometimes things go... weird... the easiest thing to do normally is just to run `stty sane` from the remote prompt.

In any case, I'm going to close this issue. While these are real problems, I don't see any way forward for `pwncat` to correctly handle all of these edge cases at the moment. It's not a great answer, and I don't like it, but it's the above is the best advice I can give. Automating everything doesn't always work. :disappointed: 

If you have other serious issues or any part of this is unrecoverable and/or you have an idea to solve the problem in the generic case, I'm open to your suggestions! :+1:

**Closed by calebstewart** 2021-05-05 03:37 UTC
Labels: bug
